### ISSUE TITLE
Remove hidden cells from student feedback files

### ISSUE THREAD

**Issue by alex-mitrevski** [DigiKlausur/e2xgrader#50]
### Problem description

In the current nbgrader version, generated student feedback files include a notebook's hidden cells. This is not always desired, particularly if a sample solution is included in the hidden cells.

### Suggested solution

Either remove hidden cells from the generated student feedback files or, perhaps better, add an option to choose whether the hidden cells should be included or not (ideally, the option should be toggled per assignment).

**Comment by tmetzl** [comment]
You can now choose to hide the source code of test cells when generating feedback. https://github.com/DigiKlausur/e2xgrader/pull/89
